### PR TITLE
add some of our values to the design doc

### PR DESCRIPTION
**Pull request by torahhorse**

### CODE REVIEW

**Comment by jacobknipfing** [comment]
Does this include online mode?

**Comment by arcanekids** [comment]
Is it possible to connect online from Wii homebrew to Linux  ?

**Comment by torahhorse** [comment]
@yuliyv  is online mode feasible

**Comment by yuliyv** [comment]
tis dependent on the engine choice

**Comment by arcanekids** [comment]
can someone please integrate these changes

**Comment by jacobknipfing** [comment]
merging with reservations

**Pull request merged**
